a = [
    "import os",
    "import time",
    "import pickle",
    "import threading",
    "import tkinter as tk",
    "from tkinter import ttk, filedialog, messagebox, Menu",
    "from PIL import Image, ImageTk",
    "import pygame",
    "from datetime import datetime",
    "from pyfirmata import Arduino",
    "from tkinter import messagebox",
    "from scipy.interpolate import interp1d",
    "import uuid",
    "from tkinter import ttk"]
